name: SSL Expiry Check

on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Run SSL check
        run: python check_ssl.py

      - name: Commit updated status
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add status.json
          git commit -m "Update SSL expiry" || exit 0
          git push
